version: '2.1'
orbs: 
  node: circleci/node@5.0.0
jobs: 
  test:
    docker:
      - image: circleci/python:3-node
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:ci
          name: Run YARN tests
      - store_test_results:
          path: test-results
workflows:
  unit-tests:
    jobs:
      - test